testParams:
  automatic: True
  work_dir: "./experiments/"
  device: "cpu"
  metrics: ["auc", "f1", "prec", "rec", "auc_class", "f1_class", "prec_class"]
  threshold: 0.5
  batch_size: 16
testDataParams:
  dataset: "chexpert"
  image_root_path: 'F:/'
  csv_path: 'F:/CheXpert-v1.0-small/valid.csv'
  image_size: [320, 320]
  image_format: 'jpeg'
  normalization: 'imagenet'
  augment: False
  mode: 'test'
  shuffle: True
  lsr_method: "dam"
  use_upsampling: False
  scan_orientation: "frontal"
  scan_projection: "all"
  train_labels: [ "Atelectasis", "Cardiomegaly", "Consolidation", "Edema", "Pleural Effusion",
                  "Enlarged Cardiomediastinum", "Lung Opacity", "Lung Lesion", "Pneumonia",
                  "Pneumothorax", "Pleural Other", "Fracture", "Support Devices" ]
augmentParams:
  randomAffine: True
  degrees: [-15, 15]
  translate: [0.05, 0.05]
  scale: [0.95, 1.05]
  fill: 128
  randomResizedCrop: False
  horizontalFlip: True
  verticalFlip: False
