testParams:
  automatic: True
  work_dir: "/home/ls6/hekalo/experiments/"
  device: "cuda"
  metrics: ["auc", "f1", "prec", "rec", "auc_class", "f1_class", "prec_class"]
  threshold: 0.5
  batch_size: 16
  overwrite: True
testDataParams:
  dataset: "chexpert"
  image_root_path: '/scratch/hekalo/Datasets/'
  csv_path: '/scratch/hekalo/Datasets/CheXpert-v1.0-small/test.csv'
  image_size: [224, 224]
  image_format: 'jpeg'
  normalization: 'imagenet'
  augment: False
  mode: 'test'
  shuffle: True
  lsr_method: "dam"
  use_upsampling: False
  scan_orientation: "frontal"
  scan_projection: "all"
  train_labels: [ "Cardiomegaly", "Edema", "Consolidation", "Atelectasis", "Pleural Effusion" ]
augmentParams:
  randomAffine: True
  degrees: [-15, 15]
  translate: [0.05, 0.05]
  scale: [0.95, 1.05]
  fill: 128
  randomResizedCrop: False
  horizontalFlip: True
  verticalFlip: False
